import unittest
import Solution
from Utility.ReturnValue import ReturnValue
from Tests.abstractTest import AbstractTest
from Business.Query import Query
from Business.RAM import RAM
from Business.Disk import Disk


class Test(AbstractTest):
    def test_Disk_add_get_and_remove(self) -> None:
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(3, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addDisk(Disk(1, "DELL", 10, 10, 10)),
                         "ID 1 ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", 0, 10, 10)), "Speed 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(0, "HP", 10, 10, 10)), "ID 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", 10, 10, 0)), "Cost 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", 10, -1, 10)), "Free space -1 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(None, "HP", 10, -1, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, None, 10, 10, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", None, 10, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", 10, None, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(4, "HP", 10, 10, None)), "NULL is not allowed")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(4, "HP", 10, 0, 10)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(1, "HP", 0, 10, 10)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addDisk(Disk(1, None, 10, 10, 10)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getDiskID(), 2, "Should work")
        self.assertEqual(disk.getCompany(), "DELL", "Should work")
        self.assertEqual(disk.getSpeed(), 10, "Should work")
        self.assertEqual(disk.getCost(), 10, "Should work")
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(4), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.deleteDisk(4), "ID 4 was already removed")
        Solution.clearTables()
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.deleteDisk(1), "Tables should be empty")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addDisk(Disk(1,"HP",1,1,1)), "Should error")
        self.assertEqual(ReturnValue.ERROR, Solution.deleteDisk(1), "Should error")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getDiskID(), None, "Should return badDisk")
        self.assertEqual(disk.getCompany(), None, "Should return badDisk")
        self.assertEqual(disk.getSpeed(), None, "Should return badDisk")
        self.assertEqual(disk.getCost(), None, "Should return badDisk")
        self.assertEqual(disk.getFreeSpace(), None, "Should return badDisk")
        Solution.createTables()
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "HP", 5, 5, 5)), "Re-adding disk 1")


    def test_RAM_add_get_and_remove(self) -> None:
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(3, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAM(RAM(1, "DELL", 10)),
                         "ID 1 ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(4, "HP", 0)), "Size 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(0, "HP", 10)), "ID 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(None, "HP", 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(4, None, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(4, "HP", None)), "NULL is not allowed")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(4, "HP", 10)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(1, "HP", 0)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addRAM(RAM(1, None, 10)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        ram = Solution.getRAMProfile(2)
        self.assertEqual(ram.getRamID(), 2, "Should work")
        self.assertEqual(ram.getCompany(), "DELL", "Should work")
        self.assertEqual(ram.getSize(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(4), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.deleteRAM(4), "ID 4 was already removed")
        Solution.clearTables()
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.deleteRAM(1), "Tables should be empty")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addRAM(RAM(1, "HP", 1)), "Should error")
        self.assertEqual(ReturnValue.ERROR, Solution.deleteRAM(1), "Should error")
        ram = Solution.getRAMProfile(1)
        self.assertEqual(ram.getRamID(), None, "Should return badRAM")
        self.assertEqual(ram.getCompany(), None, "Should return badRAM")
        self.assertEqual(ram.getSize(), None, "Should return badRAM")
        Solution.createTables()
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "HP", 5)), "Re-adding RAM 1")

    def test_Query_add_get_and_remove(self) -> None:
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "find minimum value", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "find minimum value", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "find minimum value", 10)), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addQuery(Query(1, "find minimum value", 10)),
                         "ID 1 ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(4, "find minimum value", -1)),
                         "Size -1 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(0, "find minimum value", 10)),
                         "ID 0 is illegal")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(None, "find minimum value", 10)),
                         "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(4, None, 10)), "NULL is not allowed")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(4, "find minimum value", None)),
                         "NULL is not allowed")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(4, "find minimum value", 0)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(1, "find minimum value", -1)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQuery(Query(1, None, 0)),
                         "BAD_PARAMS has precedence over ALREADY_EXISTS")
        query = Solution.getQueryProfile(2)
        self.assertEqual(query.getQueryID(), 2, "Should work")
        self.assertEqual(query.getPurpose(), "find minimum value", "Should work")
        self.assertEqual(query.getSize(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(4, "find minimum value", 0)), "Should work")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addQuery(Query(1, "HP", 1)), "Should error")
        self.assertEqual(ReturnValue.ERROR, Solution.deleteQuery(Query(1, "HP", 1)), "Should error")
        query = Solution.getQueryProfile(1)
        self.assertEqual(query.getQueryID(), None, "Should return badQuery")
        self.assertEqual(query.getPurpose(), None, "Should return badQuery")
        self.assertEqual(query.getSize(), None, "Should return badQuery")
        Solution.createTables()
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "HP", 5)), "Re-adding RAM 1")

    def test_addDiskAndQuery(self) -> None:
        self.assertEqual(ReturnValue.OK, Solution.addDiskAndQuery(Disk(1,"DELL",10,10,10),
                         Query(1,"stuff",0)), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addDiskAndQuery(Disk(1,"DELL",10,10,10),
                         Query(2,"stuff",0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2,"stuff",0)),
                         "Should work because last add should not have worked")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addDiskAndQuery(Disk(2, "DELL", 10, 10, 10),
                         Query(2, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.deleteDisk(2),"Disk should not have been added")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getDiskID(), 1, "Should work")
        self.assertEqual(disk.getCompany(), "DELL", "Should work")
        self.assertEqual(disk.getSpeed(), 10, "Should work")
        self.assertEqual(disk.getCost(), 10, "Should work")
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        query = Solution.getQueryProfile(1)
        self.assertEqual(query.getQueryID(), 1, "Should work")
        self.assertEqual(query.getPurpose(), "stuff", "Should work")
        self.assertEqual(query.getSize(), 0, "Should work")
        query = Solution.getQueryProfile(2)
        self.assertEqual(query.getQueryID(), 2, "Should work")
        self.assertEqual(query.getPurpose(), "stuff", "Should work")
        self.assertEqual(query.getSize(), 0, "Should work")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addDiskAndQuery(Disk(1, "DELL", 10, 10, 10),
                                                                  Query(1, "stuff", 0)), "Should error")
        self.assertEqual(ReturnValue.ERROR,Solution.deleteDisk(1), "Should error")
        self.assertEqual(ReturnValue.ERROR,Solution.deleteQuery(Query(1, "stuff", 0)), "Should error")

    def test_add_and_remove_query_from_disk(self):
        self.assertEqual(ReturnValue.OK, Solution.addDiskAndQuery(Disk(1, "DELL", 10, 10, 10),
                         Query(1, "stuff", 7)), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addQueryToDisk(Query(2,"stuff",0),1), "Query does not exist")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addQueryToDisk(Query(1, "stuff", 7), 2), "Disk does not exist")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 7),1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 3, "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addQueryToDisk(Query(1, "stuff", 7),1),
                         "ALREADY_EXISTS has precedence over BAD_PARAMS")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 7)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQueryToDisk(Query(2, "stuff", 7),1),
                         "Not enough space on disk")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 3)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 3), 1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 0, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(4, "stuff", 7),1),
                         "Query does not exist, but should still return OK")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(2, "stuff", 7), 1),
                         "Query is not running on disk, but should still return OK")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(1, "stuff", 7), 2),
                         "Disk does not exist, but should still return OK")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(1, "stuff", 7), 1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(3, "stuff", 3), 1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(1, "stuff", 7), 1),
                         "Query is not running on disk, but should still return OK")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(3, "stuff", 3), 1),
                         "Query is not running on disk, but should still return OK")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        Solution.clearTables()
        self.assertEqual(ReturnValue.OK, Solution.addDiskAndQuery(Disk(1, "DELL", 10, 10, 10),
                                                                  Query(1, "stuff", 3)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDiskAndQuery(Disk(2, "DELL", 10, 10, 10),
                                                                  Query(2, "stuff", 3)), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 3), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 3), 2), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(2, "stuff", 3)), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Query should have been removed from disk")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 10, "Query should have been removed from disk")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 2), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addQueryToDisk(Query(2, "stuff", 3), 1), "Query doesn't exist")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(1, "stuff", 3),1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(1, "stuff", 3)), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Query should have been removed from disk")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 10, "Query should have been removed from disk")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff",3)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 2), "Should work")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), None, "Disk was deleted")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(disk.getFreeSpace(), 7, "Disk still has query on it")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addQueryToDisk(Query(1,"stuff",1),1), "Should error")
        self.assertEqual(ReturnValue.ERROR, Solution.removeQueryFromDisk(Query(1, "stuff", 1), 1), "Should error")
        Solution.createTables()
        self.assertEqual(ReturnValue.OK, Solution.addDiskAndQuery(Disk(1, "DELL", 10, 10, 10),
                                                                  Query(1, "stuff", 7)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 7), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(1, "stuff", 7)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "stuff", 17)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQueryToDisk(Query(1, "stuff", 17), 1), "Query too big now")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "DELL", 10, 20, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 17), 1), "Disk big enough now")

    def test_add_and_remove_ram_from_disk(self):
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"DELL",10,10,10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addRAMToDisk(1,2), "Disk doesn't exist")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addRAMToDisk(2,1), "RAM doesn't exist")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAMToDisk(1, 1), "RAM is already on disk")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,2), "Disk doesn't exist")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(2,1), "RAM doesn't exist")
        self.assertEqual(ReturnValue.OK, Solution.removeRAMFromDisk(1,1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,1), "RAM was already removed")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1, 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,1),
                         "RAM should have been removed when deleted")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,1),
                         "RAM should have been removed when deleted")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,2),
                         "RAM should have been removed when deleted")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAMToDisk(2,1), "RAM is already on disk")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAMToDisk(2,2), "RAM is already on disk")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addRAMToDisk(2,1), "Disk was deleted")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAMToDisk(2,2), "RAM is already on disk")
        Solution.dropTables()
        self.assertEqual(ReturnValue.ERROR, Solution.addRAMToDisk(1, 1), "Should error")
        self.assertEqual(ReturnValue.ERROR, Solution.removeRAMFromDisk(1, 1), "Should error")

    def test_averageSizeQueriesOnDisk(self):
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "When disk doesn't exist should return 0")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"DELL", 10,15,10)), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 15, "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "When disk has no queries should return 0")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff",3)), "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "Disk still has no queries")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1,"stuff",3),1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 12, "Should work")
        self.assertEqual(3, Solution.averageSizeQueriesOnDisk(1), "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(2), "When disk doesn't exist should return 0")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 5)), "Should work")
        self.assertEqual(3, Solution.averageSizeQueriesOnDisk(1), "Disk still has 1 query of size 3")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 5), 1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addQueryToDisk(Query(3,"HP",10),1), "Query doesn't exist")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addQueryToDisk(Query(2, "stuff", 5), 1),
                         "Query is already running on disk")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(5, "stuff", 10)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQueryToDisk(Query(5, "stuff", 10), 1), "Query is too big")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 7, "Should work")
        self.assertEqual(ReturnValue.OK,Solution.removeQueryFromDisk(Query(1,"stuff",3),1), "Should work")
        self.assertEqual(5, Solution.averageSizeQueriesOnDisk(1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 10, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(2, "stuff", 5)), "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "Query should have been removed from disk")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 15, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(5, "stuff", 10), 1),"Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 1), "Should work")
        self.assertEqual(6.5, Solution.averageSizeQueriesOnDisk(1), "Should work")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getFreeSpace(), 2, "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "Disk was deleted")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(disk.getDiskID(), None, "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addQueryToDisk(Query(1, "stuff", 3), 1), "Disk doesn't exist")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "Disk doesn't exist")
        Solution.clearTables()
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "DELL", 10, 15, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "DELL", 10, 15, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "stuff", 3)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 5)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 5), 1), "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Disk 1 has 2 queries of sizes 3 and 5")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(2), "Disk 2 still has no queries")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 5), 2), "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Disk 1 has 2 queries of sizes 3 and 5")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(2), "Disk 2 has 2 queries of sizes 3 and 5")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(1, "stuff", 3), 2), "Should work")
        self.assertEqual(4, Solution.averageSizeQueriesOnDisk(1), "Disk 1 has 2 queries of sizes 3 and 5")
        self.assertEqual(5, Solution.averageSizeQueriesOnDisk(2), "Disk 2 has 1 query of size 5")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(2, "stuff", 5)), "Should work")
        self.assertEqual(3, Solution.averageSizeQueriesOnDisk(1), "Disk 1 has 1 query of size 3")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(2), "Disk 2 has no queries")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 3), 2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(0, Solution.averageSizeQueriesOnDisk(1), "Disk 1 was deleted")
        self.assertEqual(3, Solution.averageSizeQueriesOnDisk(2), "Disk 2 has 1 query of size 3")
        Solution.dropTables()
        self.assertEqual(-1, Solution.averageSizeQueriesOnDisk(1), "Should error and return -1")

    def test_diskTotalRAM(self):
        self.assertEqual(0,Solution.diskTotalRAM(1), "Disk doesn't exist, should return 0")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"DELL",10,10,10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1,"DELL",10)),"Should work")
        self.assertEqual(0,Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.addRAMToDisk(2,1), "RAM doesn't exist")
        self.assertEqual(0, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addRAMToDisk(1, 1), "RAM is already connected to disk")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(2,1), "RAM doesn't exist")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2,"DELL",10)),"Should work")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(2, 1), "RAM isn't connected to disk")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertEqual(20, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.removeRAMFromDisk(1,1),"Should work")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(10, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(2), "Should work")
        self.assertEqual(0, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertEqual(20, Solution.diskTotalRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1),"Should work")
        self.assertEqual(0, Solution.diskTotalRAM(1), "Disk doesn't exist, should return 0")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(2), "Should work")
        Solution.clearTables()
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "DELL", 10, 10, 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2, "DELL", 10)), "Should work")
        self.assertEqual(0, Solution.diskTotalRAM(1), "Disk has no RAM")
        self.assertEqual(0, Solution.diskTotalRAM(2), "Disk has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,2), "Should work")
        self.assertEqual(20, Solution.diskTotalRAM(1), "Disk 1 has 2 RAM of size 10 each")
        self.assertEqual(20, Solution.diskTotalRAM(2), "Disk 2 has 2 RAM of size 10 each")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(10, Solution.diskTotalRAM(1), "1 RAM should have been removed when deleted")
        self.assertEqual(10, Solution.diskTotalRAM(2), "1 RAM should have been removed when deleted")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1, "DELL", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1, 1), "Should work")
        self.assertEqual(20, Solution.diskTotalRAM(1), "Disk 1 has 2 RAM of size 10 each")
        self.assertEqual(10, Solution.diskTotalRAM(2), "Disk 2 has 1 RAM of size 10")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertEqual(10, Solution.diskTotalRAM(1), "1 RAM should have been removed when deleted")
        self.assertEqual(10, Solution.diskTotalRAM(2), "Disk 2 should not have changed")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(0, Solution.diskTotalRAM(1), "Disk 1 was deleted")
        self.assertEqual(10, Solution.diskTotalRAM(2), "Disk 2 should not have changed")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(2), "Should work")
        Solution.dropTables()
        self.assertEqual(-1, Solution.diskTotalRAM(1), "Should error and return -1")

    def test_getCostForPurpose(self):
        self.assertEqual(0,Solution.getCostForPurpose("stuff"), "Purpose doesn't exist, should return 0")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff", 5)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"HP",10,15,10)), "Should work")
        self.assertEqual(0, Solution.getCostForPurpose("stuff"), "Query isn't running")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1,"stuff",5),1), "Should work")
        self.assertEqual(50, Solution.getCostForPurpose("stuff"), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 2)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "HP", 10, 15, 10)), "Should work")
        self.assertEqual(50, Solution.getCostForPurpose("stuff"), "Query 2 isn't running")
        self.assertEqual(ReturnValue.ALREADY_EXISTS, Solution.addQueryToDisk(Query(1, "stuff", 5), 1),
                         "Query is already running on disk")
        self.assertEqual(50, Solution.getCostForPurpose("stuff"), "Query 2 isn't running")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 2), 1), "Should work")
        self.assertEqual(70, Solution.getCostForPurpose("stuff"), "2 queries running")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 1), 2), "Should work")
        self.assertEqual(80, Solution.getCostForPurpose("stuff"), "3 queries running")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 2), 2), "Should work")
        self.assertEqual(100, Solution.getCostForPurpose("stuff"), "3 queries running (1 is running on 2 disks)")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(4, "other stuff", 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(5, "other stuff", 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(4, "other stuff", 1), 1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(4, "other stuff", 1), 2), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(5, "other stuff", 1), 2), "Should work")
        self.assertEqual(100, Solution.getCostForPurpose("stuff"), "new queries have different purpose")
        self.assertEqual(30, Solution.getCostForPurpose("other stuff"), "new queries")
        disk = Solution.getDiskProfile(1)
        self.assertEqual(7, disk.getFreeSpace(), "Should work")
        disk = Solution.getDiskProfile(2)
        self.assertEqual(10, disk.getFreeSpace(), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(6, "stuff", 10)), "Should work")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQueryToDisk(Query(6, "other stuff", 10), 1),
                         "Query too big")
        self.assertEqual(100, Solution.getCostForPurpose("stuff"), "Query 6 should not run")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(6, "stuff", 10), 2), "Should work")
        self.assertEqual(200, Solution.getCostForPurpose("stuff"), "Query 6 now running")
        self.assertEqual(30, Solution.getCostForPurpose("other stuff"), "Shouldn't have changed")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(4, "other stuff", 1)), "Should work")
        self.assertEqual(200, Solution.getCostForPurpose("stuff"), "Shouldn't have changed")
        self.assertEqual(10, Solution.getCostForPurpose("other stuff"), "Query 4 was deleted")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual(130, Solution.getCostForPurpose("stuff"), "Queries that ran on disk 1 should have been removed")
        self.assertEqual(10, Solution.getCostForPurpose("other stuff"),
                         "Shouldn't have changed. Disk 1 ran no queries with this purpose")
        Solution.dropTables()
        self.assertEqual(-1, Solution.getCostForPurpose("stuff"), "Should error and return -1")

    def test_getQueriesCanBeAddedToDisk(self):
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDisk(1), "Disk doesn't exist. Should return empty list")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"HP",10,10,10)),"Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2,"HP",10,20,10)),"Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDisk(1), "No queries")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDisk(2), "No queries")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff",3)), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDisk(1), "Query 1 now available")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDisk(2), "Query 1 now available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 3)), "Should work")
        self.assertListEqual([3,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 3 should be first, descending order")
        self.assertListEqual([3,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 3 should be first, descending order")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 3)), "Should work")
        self.assertListEqual([3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Descending")
        self.assertListEqual([3,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Descending")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(4, "stuff", 13)), "Should work")
        self.assertListEqual([3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 4 is too big for disk 1")
        self.assertListEqual([4,3,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 4 now available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(5, "stuff", 23)), "Should work")
        self.assertListEqual([3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 5 is too big for disk 1")
        self.assertListEqual([4,3,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 5 is too big for disk 2")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(8, "other stuff", 3)), "Should work")
        self.assertListEqual([8,3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 8 now available")
        self.assertListEqual([8,4,3,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 8 now available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(10, "stuff", 3)), "Should work")
        self.assertListEqual([10,8,3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 10 now available")
        self.assertListEqual([10,8,4,3,2], Solution.getQueriesCanBeAddedToDisk(2), "Query 10 now available")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(4, "stuff", 13)), "Should work")
        self.assertListEqual([10,8,3,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Shouldn't change")
        self.assertListEqual([10,8,3,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 4 deleted")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(3, "stuff", 3)), "Should work")
        self.assertListEqual([10,8,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 3 deleted")
        self.assertListEqual([10,8,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 3 deleted")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(15, "stuff", 3)), "Should work")
        self.assertListEqual([15,10,8,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 15 now available")
        self.assertListEqual([15,10,8,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 15 now available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(20, "stuff", 3)), "Should work")
        self.assertListEqual([20,15,10,8,2], Solution.getQueriesCanBeAddedToDisk(1), "Query 20 now available")
        self.assertListEqual([20,15,10,8,2], Solution.getQueriesCanBeAddedToDisk(2), "Query 20 now available")
        self.assertEqual(ReturnValue.OK,Solution.deleteQuery(Query(10, "stuff", 3)), "Should work")
        self.assertListEqual([20,15,8,2,1], Solution.getQueriesCanBeAddedToDisk(1), "Query 10 deleted")
        self.assertListEqual([20,15,8,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Query 10 deleted")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(1), "Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDisk(1), "Disk 1 was deleted")
        self.assertListEqual([20,15,8,2,1], Solution.getQueriesCanBeAddedToDisk(2), "Shouldn't change")
        Solution.dropTables()
        self.assertEqual([],Solution.getQueriesCanBeAddedToDisk(1),"Should error and return empty list")

    def test_getQueriesCanBeAddedToDiskAndRAM(self):
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk doesn't exist. Should return empty list")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"HP",10,10,10)),"Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2,"HP",10,20,10)),"Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "No queries")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "No queries")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff",3)), "Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk 1 has no RAM")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1,"HP",10)), "Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk 1 has no RAM")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 has no RAM")
        self.assertEqual(ReturnValue.OK,Solution.addRAMToDisk(1,1), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk 1 now has 10 RAM")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 still has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2, "HP", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,2), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Shouldn't change")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 now has 10 RAM")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 15)), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Not enough free space for query 2")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Not enough RAM for query 2")
        self.assertEqual(ReturnValue.OK, Solution.removeRAMFromDisk(2,2), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Shouldn't change")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 now has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,2), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Shouldn't change")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 now has 10 RAM")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(2), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk 1 should still have 10 RAM")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 now has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,2), "Should work")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(2), "Should work")
        self.assertListEqual([1], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Shouldn't change")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(2), "Disk 2 was deleted")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(5, "stuff", 3)), "Should work")
        self.assertListEqual([1,5], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Query 5 available, ascending")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 3)), "Should work")
        self.assertListEqual([1,3,5], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Query 3 available, ascending")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(10, "stuff", 3)), "Should work")
        self.assertListEqual([1,3,5,10], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Query 10 available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(20, "stuff", 3)), "Should work")
        self.assertListEqual([1,3,5,10,20], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Query 20 available")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(15, "stuff", 3)), "Should work")
        self.assertListEqual([1,3,5,10,15], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Max 5")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(15, "stuff", 3)), "Should work")
        self.assertListEqual([1,3,5,10,20], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Query 15 deleted")
        self.assertEqual(ReturnValue.OK,Solution.addQueryToDisk(Query(20, "stuff", 3),1), "Should work")
        self.assertListEqual([1, 3, 5, 10, 20], Solution.getQueriesCanBeAddedToDiskAndRAM(1),
                             "List can include queries already running on disk")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(1), "Should work")
        self.assertListEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk 1 now has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(7, "stuff", 0)), "Should work")
        self.assertListEqual([7],Solution.getQueriesCanBeAddedToDiskAndRAM(1),
                             "Query 7 requires no space, so can be added to RAM even if there is no RAM")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1), "Should work")
        self.assertEqual([],Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Disk doesn't exist")
        Solution.dropTables()
        self.assertEqual([], Solution.getQueriesCanBeAddedToDiskAndRAM(1), "Should error and return empty list")

    def test_isCompanyExclusive(self):
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk doesn't exist")
        self.assertEqual(ReturnValue.OK,Solution.addDisk(Disk(1,"HP",1,1,1)), "Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "Disk has no RAM and therefore is company exclusive")
        self.assertEqual(ReturnValue.OK,Solution.addRAM(RAM(1,"DELL",1)),"Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "RAM isn't connected")
        self.assertEqual(ReturnValue.OK,Solution.addRAMToDisk(1,1),"Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk from hp has RAM from dell")
        self.assertEqual(ReturnValue.OK,Solution.removeRAMFromDisk(1,1),"Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "RAM was disconnected")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1, 1), "Should work")
        self.assertEqual(ReturnValue.OK,Solution.deleteRAM(1),"should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "RAM was deleted")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(1,"HP",1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(1,1), "Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "Disk and RAM are from HP")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(2,"HP",1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,1), "Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "2 RAMs from HP")
        self.assertEqual(ReturnValue.OK, Solution.addRAM(RAM(3,"DELL",1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(3,1), "Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk from hp with RAM from dell")
        self.assertEqual(ReturnValue.OK,Solution.addDisk(Disk(2,"DELL",1,1,1)),"Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk 1 from hp with RAM from dell")
        self.assertTrue(Solution.isCompanyExclusive(2), "Disk 2 has no RAM")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(3,2), "Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk 1 from hp with RAM from dell")
        self.assertTrue(Solution.isCompanyExclusive(2), "Disk 2 from dell with RAM from dell")
        self.assertEqual(ReturnValue.OK, Solution.addRAMToDisk(2,2), "Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk 1 from hp with RAM from dell")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk 2 from dell with RAM from hp")
        self.assertEqual(ReturnValue.NOT_EXISTS, Solution.removeRAMFromDisk(1,2), "Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Shouldn't change")
        self.assertFalse(Solution.isCompanyExclusive(1), "Shouldn't change")
        self.assertEqual(ReturnValue.OK,Solution.deleteRAM(1),"Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Shouldn't change")
        self.assertFalse(Solution.isCompanyExclusive(1), "Shouldn't change")
        self.assertEqual(ReturnValue.OK, Solution.deleteRAM(3), "Should work")
        self.assertTrue(Solution.isCompanyExclusive(1), "RAM from dell was deleted")
        self.assertFalse(Solution.isCompanyExclusive(2), "Still from dell with RAM from hp")
        self.assertEqual(ReturnValue.OK, Solution.deleteDisk(1),"Should work")
        self.assertFalse(Solution.isCompanyExclusive(1), "Disk was deleted")
        self.assertFalse(Solution.isCompanyExclusive(2), "Shouldn't change")
        Solution.dropTables()
        self.assertFalse(Solution.isCompanyExclusive(1), "Should error and return False")

    def test_getConflictingDisks(self):
        self.assertEqual([], Solution.getConflictingDisks(), "No disks available")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1,"HP",1,10,1)),"Should work")
        self.assertEqual([], Solution.getConflictingDisks(), "No conflicting disks")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2,"HP",1,10,1)), "Should work")
        self.assertEqual([], Solution.getConflictingDisks(), "No conflicting disks")
        self.assertEqual(ReturnValue.OK,Solution.addQuery(Query(1,"stuff",2)),"Should work")
        self.assertEqual([], Solution.getConflictingDisks(), "No conflicting disks")
        self.assertEqual(ReturnValue.OK,Solution.addQueryToDisk(Query(1,"stuff",2),1), "Should work")
        self.assertEqual([], Solution.getConflictingDisks(), "No conflicting disks")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 2),2), "Should work")
        self.assertEqual([1,2], Solution.getConflictingDisks(), "Disks 1,2 both run query 1")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(3, "HP", 1, 10, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 2), 3), "Should work")
        self.assertEqual([1,2,3], Solution.getConflictingDisks(),
                         "Disks 1,2,3 all run query 1 and should each appear once in the list")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(4, "HP", 1, 1, 1)), "Should work")
        self.assertEqual([1,2,3], Solution.getConflictingDisks(), "Disk 4 is not conflicting")
        self.assertEqual(ReturnValue.BAD_PARAMS, Solution.addQueryToDisk(Query(1, "stuff", 2), 4),
                         "Disk 4 doesn't have enough free space")
        self.assertEqual([1,2,3], Solution.getConflictingDisks(), "Shouldn't change")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2,"stuff",1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2,"stuff",1),4),"Should work")
        self.assertEqual([1,2,3], Solution.getConflictingDisks(), "Disk 4 is not conflicting")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2,"stuff",1),2),"Should work")
        self.assertEqual([1,2,3,4], Solution.getConflictingDisks(), "Disk 4 is now conflicting with disk 2")
        self.assertEqual(ReturnValue.OK,Solution.removeQueryFromDisk(Query(1, "stuff", 2),1),"Should work")
        self.assertEqual([2,3,4], Solution.getConflictingDisks(), "Disk 1 no longer conflicts")
        self.assertEqual(ReturnValue.OK,Solution.deleteQuery(Query(1, "stuff", 2)),"Should work")
        self.assertEqual([2,4], Solution.getConflictingDisks(),
                         "Disk 3 no longer conflicts due to query 1 being deleted")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2,"stuff",1),3), "Should work")
        self.assertEqual([2,3,4], Solution.getConflictingDisks(), "Disk 3 is now conflicting")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(2,"stuff",1),3), "Should work")
        self.assertEqual([2,4], Solution.getConflictingDisks(), "Disk 3 is no longer conflicting")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1,"stuff",5)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1,"stuff",5),3), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1,"stuff",5), 1), "Should work")
        self.assertEqual([1,2,3,4], Solution.getConflictingDisks(),
                         "Disk 1 conflicts with 3 and disk 2 conflicts with 4")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(1),"Should work")
        self.assertEqual([2,4], Solution.getConflictingDisks(),
                         "Disk 1 deleted, therefore Disk 3 is no longer conflicting")
        Solution.dropTables()
        self.assertEqual([],Solution.getConflictingDisks(),"Should error and return empty list")

    def test_mostAvailableDisks(self):
        self.assertListEqual([],Solution.mostAvailableDisks(),"No disks")
        self.assertEqual(ReturnValue.OK,Solution.addDisk(Disk(1,"HP",1,1,1)),"Should work")
        self.assertListEqual([1],Solution.mostAvailableDisks(),"Can run 0 queries")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(5, "HP", 1, 4, 1)), "Should work")
        self.assertListEqual([1,5], Solution.mostAvailableDisks(), "ascending")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(3, "HP", 1, 10, 1)), "Should work")
        self.assertListEqual([1,3,5], Solution.mostAvailableDisks(), "ascending")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "HP", 5, 2, 1)), "Should work")
        self.assertListEqual([2, 1, 3, 5], Solution.mostAvailableDisks(), "Disk 2 is faster")
        self.assertEqual(ReturnValue.OK,Solution.addQuery(Query(1,"stuff",10)),"Should work")
        self.assertListEqual([3, 2, 1, 5], Solution.mostAvailableDisks(), "Disk 3 is the only one who can run query 1")
        self.assertEqual(ReturnValue.OK,Solution.addQueryToDisk(Query(1,"stuff",10),3),"Should work")
        self.assertListEqual([2, 1, 3, 5], Solution.mostAvailableDisks(), "Disk 3 is full")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 1)), "Should work")
        self.assertListEqual([2, 1, 5, 3], Solution.mostAvailableDisks(), "All disks other than 3 can run query 2")
        self.assertEqual(ReturnValue.OK,Solution.removeQueryFromDisk(Query(1,"stuff",10),3),"should work")
        self.assertListEqual([3, 2, 1, 5], Solution.mostAvailableDisks(), "Disk 3 can run both queries")
        self.assertEqual(ReturnValue.OK,Solution.deleteQuery(Query(1,"stuff",10)),"Should work")
        self.assertListEqual([2, 1, 3, 5], Solution.mostAvailableDisks(), "All disks can run query 1")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "stuff", 10)), "Should work")
        self.assertListEqual([3, 2, 1, 5], Solution.mostAvailableDisks(), "Disk 3 can run both queries")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 10), 3), "Should work")
        self.assertListEqual([2, 1, 5, 3], Solution.mostAvailableDisks(),
                             "Disk 3 can't run query 1 again (not enough space")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(1, "stuff", 10)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.deleteQuery(Query(2, "stuff", 1)), "Should work")
        self.assertListEqual([2, 1, 3, 5], Solution.mostAvailableDisks(), "No queries")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(5, "stuff", 2)), "Should work")
        self.assertListEqual([2, 3, 5, 1], Solution.mostAvailableDisks(), "Disk 1 can't run query 5")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(5, "stuff", 2), 2), "Should work")
        self.assertListEqual([3, 5, 2, 1], Solution.mostAvailableDisks(),
                             "Disk 2 is full, but disk 1 can't run any queries either and is slower")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(5, "stuff", 2), 5), "Should work")
        self.assertListEqual([3, 5, 2, 1], Solution.mostAvailableDisks(),
                             "Disk 5 still has enough space to run the query again")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(5, "stuff", 2), 2), "should work")
        self.assertListEqual([2, 3, 5, 1], Solution.mostAvailableDisks(), "Disk 1 can't run query 5")
        self.assertEqual(ReturnValue.NOT_EXISTS,Solution.addQueryToDisk(Query(10,"stuff",2),2),"No such query")
        self.assertListEqual([2, 3, 5, 1], Solution.mostAvailableDisks(), "Shouldn't change")
        Solution.clearTables()
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(1, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(2, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(3, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(4, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(5, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(6, "HP", 1, 1, 1)), "Should work")
        self.assertListEqual([1,2,3,4,5], Solution.mostAvailableDisks(), "Max 5 disks")
        Solution.dropTables()
        self.assertListEqual([], Solution.mostAvailableDisks(), "Should error and return empty list")

    def test_getCloseQueries(self):
        self.assertEqual(ReturnValue.OK,Solution.addQuery(Query(1,"stuff",0)),"Should work")
        self.assertListEqual([], Solution.getCloseQueries(1), "Query can't be close to itself")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 0)), "Should work")
        self.assertListEqual([2],Solution.getCloseQueries(1),"Close in an empty sense")
        self.assertListEqual([1], Solution.getCloseQueries(2), "Close in an empty sense")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 0)), "Should work")
        self.assertListEqual([2,3], Solution.getCloseQueries(1), "Close in an empty sense")
        self.assertListEqual([1,3], Solution.getCloseQueries(2), "Close in an empty sense")
        self.assertListEqual([1,2], Solution.getCloseQueries(3), "Close in an empty sense")
        self.assertEqual(ReturnValue.OK,Solution.addDisk(Disk(1,"HP",1,1,1)),"Should work")
        self.assertListEqual([2, 3], Solution.getCloseQueries(1), "Shouldn't change")
        self.assertListEqual([1, 3], Solution.getCloseQueries(2), "Shouldn't change")
        self.assertListEqual([1, 2], Solution.getCloseQueries(3), "Shouldn't change")
        self.assertEqual(ReturnValue.OK,Solution.addQueryToDisk(Query(1,"stuff",0),1),"Should work")
        self.assertListEqual([], Solution.getCloseQueries(1), "Can't be Close in an empty sense any more")
        self.assertListEqual([1,3], Solution.getCloseQueries(2), "Still close in an empty sense")
        self.assertListEqual([1,2], Solution.getCloseQueries(3), "Still close in an empty sense")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 0), 1), "Should work")
        self.assertListEqual([2], Solution.getCloseQueries(1), "Queries 1 and 2 run on same disk")
        self.assertListEqual([1], Solution.getCloseQueries(2), "Queries 1 and 2 run on same disk")
        self.assertListEqual([1, 2], Solution.getCloseQueries(3), "Still close in an empty sense")
        self.assertEqual(ReturnValue.OK,Solution.addDisk(Disk(2,"HP",1,1,1)),"Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 0), 2), "Should work")
        self.assertListEqual([2], Solution.getCloseQueries(1), "Shouldn't change")
        self.assertListEqual([1], Solution.getCloseQueries(2), "Shouldn't change")
        self.assertListEqual([], Solution.getCloseQueries(3), "Can't be Close in an empty sense any more")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 0), 1), "Should work")
        self.assertListEqual([2, 3], Solution.getCloseQueries(1), "Everyone is running on disk 1")
        self.assertListEqual([1, 3], Solution.getCloseQueries(2), "Everyone is running on disk 1")
        self.assertListEqual([1, 2], Solution.getCloseQueries(3), "Everyone is running on disk 1, which is 50%")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(3, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 0), 3), "Should work")
        self.assertListEqual([2, 3], Solution.getCloseQueries(1), "Shouldn't change")
        self.assertListEqual([1, 3], Solution.getCloseQueries(2), "Shouldn't change")
        self.assertListEqual([], Solution.getCloseQueries(3), "Not 50% any more")
        self.assertEqual(ReturnValue.OK, Solution.addDisk(Disk(4, "HP", 1, 1, 1)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(3, "stuff", 0), 4), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 0), 2), "Should work")
        self.assertListEqual([2, 3], Solution.getCloseQueries(1), "Everyone is running on disk 1")
        self.assertListEqual([1, 3], Solution.getCloseQueries(2), "Everyone is running on disk 1, which is 50%")
        self.assertListEqual([2], Solution.getCloseQueries(3), "Exactly 50%")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(1, "stuff", 0), 4), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQueryToDisk(Query(2, "stuff", 0), 4), "Should work")
        self.assertListEqual([1,2], Solution.getCloseQueries(3), "2 is closer but should be ordered by id")
        self.assertEqual(ReturnValue.OK,Solution.deleteDisk(4),"Should work")
        self.assertListEqual([2,3], Solution.getCloseQueries(1), "Everyone is running on disk 1")
        self.assertListEqual([1,3], Solution.getCloseQueries(2), "Everyone is running on disk 1, which is 50%")
        self.assertListEqual([2], Solution.getCloseQueries(3), "2 is running on 2 and 3")
        self.assertEqual(ReturnValue.OK,Solution.deleteQuery(Query(2, "stuff", 0)),"Should work")
        self.assertListEqual([3], Solution.getCloseQueries(1), "Query 2 deleted")
        self.assertListEqual([], Solution.getCloseQueries(3), "Query 2 deleted")
        self.assertEqual(ReturnValue.OK, Solution.removeQueryFromDisk(Query(3, "stuff", 0), 2), "Should work")
        self.assertListEqual([3], Solution.getCloseQueries(1), "Shouldn't change")
        self.assertListEqual([1], Solution.getCloseQueries(3), "1 is now close")
        Solution.clearTables()
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(1, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(12, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(8, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(54, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(9, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(2, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(23, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(7, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(10, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(11, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(3, "stuff", 0)), "Should work")
        self.assertEqual(ReturnValue.OK, Solution.addQuery(Query(15, "stuff", 0)), "Should work")
        self.assertListEqual([1, 2, 7, 8, 9, 10, 11, 12, 15, 23], Solution.getCloseQueries(3),
                             "Max 10, should not include 3 itself")


# *** DO NOT RUN EACH TEST MANUALLY ***
if __name__ == '__main__':
    unittest.main(verbosity=2, exit=False)
